PROJECT_DIR := $(shell pwd)

MUSL_TOOLCHAIN_PREFIX := riscv64-linux-musl
MUSL_TOOLCHAIN_DIR := $(PROJECT_DIR)/$(MUSL_TOOLCHAIN_PREFIX)-cross/bin
MUSL_CC := $(MUSL_TOOLCHAIN_PREFIX)-gcc
MUSL_AR := $(MUSL_TOOLCHAIN_PREFIX)-ar
MUSL_OBJCOPY := $(MUSL_TOOLCHAIN_PREFIX)-objcopy

BASH_DIR := $(PROJECT_DIR)/bash-5.1.16
BASH := $(BASH_DIR)/bash

export PATH := $(PATH):$(MUSL_TOOLCHAIN_DIR)

$(BASH):
	cd $(BASH_DIR) && make 
	$(MUSL_OBJCOPY) --strip-debug $(BASH)

all: $(BASH)	
